### ISSUE TITLE
Utilize the collections feature 

### ISSUE THREAD

**Issue by nullgat** [r-anime/holo#37]
Starting in Summer 2019 the bot should utilize the new reddit [collections feature](https://www.reddit.com/r/modnews/comments/bgibu9/an_update_on_making_it_easier_to_host_events_on/). [API](https://www.reddit.com/dev/api/#section_collections)

**Comment by ifonefox** [comment]
Wouldn't the bot need to be a moderator of /r/anime?

**Comment by Geo1088** [comment]
Correct, it looks like the bot must be a moderator with "post" permissions to manipulate collections. I don't think that should be an issue, but we'll have to talk it over since we also have non-moderators with access to the account.

If we decide we don't want the bot account to be a mod, it could always be done by authorizing with /u/AnimeMod to do the collection modification after the post is made on /u/AutoLovepon, but that would probably be a fair amount of extra effort.

**Comment by bainosz** [comment]
Using a separate account such as /u/AnimeMod to manage the collections feature wouldn't be too difficult - it was already done in a separate branch to add the poll links in a sticky comment.

I'm more worried about having to support this feature on the Redesign -- which means it's still a beta feature (whether Reddit calls it that or not) with no backward compatibility to old.reddit.com, and that it creates overhead for the human users who manually create posts (and, as Geo mentioned, we have non-mods in the team).

I agree that the bot should start using this feature, but I don't think it will be as soon as Summer 2019.

**Comment by bainosz** [comment]
This possible enhancement has been left on the backlog for a long time to see how the collections feature would end up looking. In the end, given its format (which is strongly focused on the post itself and not the comment section), it's a very poor fit for episode discussions where comments are the most important part of a discussion.

Consequently, I have decided to close this suggestion, as it won't be implemented.
