### ISSUE TITLE
Add redirection to cross-sub source thread

### ISSUE THREAD

**Issue by adethise** [r-anime/holo#9]
Suggested [in this comment.](https://www.reddit.com/r/anime/comments/857sqf/meta_thread_month_of_march_18_2018/dwytusk/)

**Comment by adethise** [comment]
The first step would be to add a redirection to the appropriate sub. Could be done at the same time as adding "official site" information ?

**Comment by adethise** [comment]
I don't know if making it generic is required. So far we already have 4 services (although I didn't use Kitsu for this season, so it's essentially 3). If we add 'official' and 'subreddit', I think we will have quite enough metadata information - more would make the post cluttered.

Anyway, I'll leave the implementation up to you. Please ping me if there is a significant update to the database structure so that I can migrate safely.

**Comment by Geo1088** [comment]
That's true, I thought that to myself a bit after I commented that, looking through the code. I'll look into it.

**Comment by vaclav-2012** [comment]
> If we add 'official' and 'subreddit', I think we will have quite enough metadata information - more would make the post cluttered.

I'm not sure for how many shows this would apply, but Slow Start from the last season had [nice and informative official website](http://slow-start.com/) and also [US website](http://slowstart-usa.com/) with less information but translated into English. I have been visiting both sites during the season.

**Comment by Geo1088** [comment]
Yeah, situations like that were kinda what I was thinking about when I said "general metadata"... then again, I guess we could just have "Official site", "English site", and "Community/Subreddit" fields that all use the same link format as we have now.

**Comment by vaclav-2012** [comment]
In general, the considered approach of storing universal metadata would make sense to me, but take my opinion with a grain of salt. I'm not a Python developer and I have just quickly reviewed the code (it looks quite readable).

In the context of the current data structure, adding Subreddit as another LinkSite would sound reasonable since it's represented by a "site_key" within Reddit. Other websites wouldn't fit this structure. I can imagine they could be stored as some generic Website (with a related InfoHandler class), but that would seem like a bit workaround. And in case the DB would be modified I may be worth a consideration to make it more universal.

**Comment by Geo1088** [comment]
@vaclav-2012 Haha, I'm not really a Python developer either to be honest. I like your comment on the structure though. I think I'll do it that way, with "Reddit" designated as an info site and a subreddit name used as `site_key`, and then #1 will be its own thing to support arbitrary information fields/links/markdown content/etc.

**Comment by adethise** [comment]
Merged into #19
